---
- name: Ubuntu VM Configuration
  hosts: ubuntuvm
  become: true
  vars:
    cowsay_package_name: cowsay

  tasks:
  - name: Install cowsay
    tags: packages
    ansible.builtin.apt:
      name: "{{ cowsay_package_name }}"
      state: present
      update_cache: true
  - name: add newuser
    tags: users
    ansible.builtin.user:
      name: newuser
  - name: grant newuser sudo access
    tags: user
    community.general.sudoers:
      name: newuser-restart
      user: newuser
      commands: /usr/bin/systemctl restart cron